import json
import os
from datetime import datetime
from pathlib import Path

# Template storage location
TEMPLATES_DIR = Path(__file__).parent.parent / "data" / "invoice_templates"
TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)

DEFAULT_TEMPLATE = {
    "name": "Default",
    "is_default": True,
    "title": "USIZO Loan Invoice",
    "title_font": "Arial",
    "title_size": 14,
    "title_bold": True,
    "heading_font": "Arial",
    "heading_size": 11,
    "heading_bold": True,
    "body_font": "Arial",
    "body_size": 10,
    "body_bold": False,
    "include_sections": {
        "client_info": True,
        "loan_details": True,
        "payment_history": True,
        "company_footer": True
    },
    "client_info_fields": {
        "first_name": True,
        "last_name": True,
        "id_number": True,
        "phone": True
    },
    "loan_details_fields": {
        "loan_id": True,
        "principal": True,
        "balance": True,
        "amount_paid": True,
        "due_date": True,
        "status": True
    },
    "payment_history_fields": {
        "date": True,
        "amount": True,
        "type": True
    },
    "colors": {
        "heading": (0, 0, 0),
        "body": (0, 0, 0),
        "table_header": (200, 200, 200)
    },
    "company_footer": "Generated by FUS30 Suite"
}

def get_templates_dir():
    """Return templates directory path"""
    return TEMPLATES_DIR

def save_template(template):
    """Save a template to disk"""
    template_name = template.get("name", "Untitled")
    template_file = TEMPLATES_DIR / f"{template_name}.json"
    
    with open(template_file, 'w') as f:
        json.dump(template, f, indent=2)
    
    return template_file

def load_template(template_name):
    """Load a template from disk"""
    template_file = TEMPLATES_DIR / f"{template_name}.json"
    
    if template_file.exists():
        with open(template_file, 'r') as f:
            return json.load(f)
    return None

def get_all_templates():
    """Get list of all saved templates"""
    templates = []
    
    if TEMPLATES_DIR.exists():
        for template_file in TEMPLATES_DIR.glob("*.json"):
            with open(template_file, 'r') as f:
                templates.append(json.load(f))
    
    # Always include default if no templates exist
    if not templates:
        templates.append(DEFAULT_TEMPLATE)
    
    return sorted(templates, key=lambda x: x.get("is_default", False), reverse=True)

def get_default_template():
    """Get the default template"""
    templates = get_all_templates()
    for template in templates:
        if template.get("is_default", False):
            return template
    
    # If no default found, return the first one or DEFAULT_TEMPLATE
    return templates[0] if templates else DEFAULT_TEMPLATE

def set_default_template(template_name):
    """Set a template as default"""
    templates = get_all_templates()
    
    for template in templates:
        if template.get("name") == template_name:
            template["is_default"] = True
        else:
            template["is_default"] = False
        save_template(template)

def delete_template(template_name):
    """Delete a template"""
    template_file = TEMPLATES_DIR / f"{template_name}.json"
    
    if template_file.exists() and template_name != "Default":
        template_file.unlink()
        return True
    return False

def create_blank_template(name):
    """Create a blank template based on DEFAULT_TEMPLATE"""
    template = DEFAULT_TEMPLATE.copy()
    template["name"] = name
    template["is_default"] = False
    return template
